"""Multi-image chat messages: chat_message_images table + backfill + drop single-image cols

Revision ID: 0d5e2a36f74c
Revises: bb7aae3428a8
Create Date: 2026-04-28 16:31:26.969537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d5e2a36f74c'
down_revision = 'bb7aae3428a8'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Create the new chat_message_images table
    op.create_table(
        'chat_message_images',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('message_id', sa.Integer(), nullable=False),
        sa.Column('image_data', sa.LargeBinary(), nullable=False),
        sa.Column('image_mime', sa.String(length=64), nullable=True),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('chat_message_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_images_message_id'), ['message_id'], unique=False)

    # 2. Backfill: copy any existing single-image rows into the new table
    # Doing this in raw SQL because we want it to run inside the same migration transaction.
    op.execute("""
        INSERT INTO chat_message_images (message_id, image_data, image_mime, "order", created_at)
        SELECT id, image_data, image_mime, 0, created_at
        FROM chat_messages
        WHERE image_data IS NOT NULL
    """)

    # 3. Drop the now-redundant single-image columns from chat_messages
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('image_mime')
        batch_op.drop_column('image_data')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_mime', sa.VARCHAR(length=64), autoincrement=False, nullable=True))

    with op.batch_alter_table('chat_message_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_images_message_id'))

    op.drop_table('chat_message_images')
    # ### end Alembic commands ###
