"""Add institution verification fields

Revision ID: 36fff8db06f1
Revises: b418199aa720
Create Date: 2026-03-01 17:14:13.890499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36fff8db06f1'
down_revision = 'b418199aa720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('institution_domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institution_domains_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_institution_domains_institution_id'), ['institution_id'], unique=False)

    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_from_dataset', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('alpha_two_code', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('state_province', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('web_pages', sa.JSON(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution_verified', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('verification_domain', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_domain')
        batch_op.drop_column('institution_verified')

    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_column('web_pages')
        batch_op.drop_column('state_province')
        batch_op.drop_column('alpha_two_code')
        batch_op.drop_column('country')
        batch_op.drop_column('is_from_dataset')

    with op.batch_alter_table('institution_domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institution_domains_institution_id'))
        batch_op.drop_index(batch_op.f('ix_institution_domains_domain'))

    op.drop_table('institution_domains')
    # ### end Alembic commands ###
