"""Add last_pause_action_at to TeachingAssistant for billing abuse prevention

Revision ID: 5cff802fc147
Revises: aa520fe64dc9
Create Date: 2026-02-23 21:31:44.911732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cff802fc147'
down_revision = 'aa520fe64dc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teaching_assistants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_pause_action_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teaching_assistants', schema=None) as batch_op:
        batch_op.drop_column('last_pause_action_at')

    # ### end Alembic commands ###
