"""Add TA status and published_at

Revision ID: 8345109cf060
Revises: 36fff8db06f1
Create Date: 2026-03-01 18:10:20.459297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8345109cf060'
down_revision = '36fff8db06f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teaching_assistants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=16), server_default='draft', nullable=False))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))

    # Data migration: set status for existing TAs
    op.execute("""
        UPDATE teaching_assistants
        SET status = 'active', published_at = created_at
        WHERE stripe_subscription_id IS NOT NULL AND NOT is_paused
    """)
    op.execute("""
        UPDATE teaching_assistants
        SET status = 'paused'
        WHERE stripe_subscription_id IS NOT NULL AND is_paused
    """)
    op.execute("""
        UPDATE teaching_assistants
        SET status = 'active', published_at = created_at
        WHERE requires_billing = false AND status = 'draft'
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teaching_assistants', schema=None) as batch_op:
        batch_op.drop_column('published_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
