"""Add email_verified to users

Revision ID: 8e18e94b1c5a
Revises: 93658099e0d6
Create Date: 2026-02-24 23:08:23.100528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e18e94b1c5a'
down_revision = '93658099e0d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='false'))

    # Trust all pre-existing users — they signed up before email verification was enforced
    op.execute('UPDATE users SET email_verified = TRUE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
