"""Add Auth0 support

Revision ID: 93658099e0d6
Revises: 5cff802fc147
Create Date: 2026-02-24 22:03:55.919968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93658099e0d6'
down_revision = '5cff802fc147'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth0_states',
    sa.Column('state', sa.String(length=256), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('auth0_transactions',
    sa.Column('nonce', sa.String(length=256), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('nonce')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth0_sub', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_auth0_sub'), ['auth0_sub'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_auth0_sub'))
        batch_op.drop_column('auth0_sub')

    op.drop_table('auth0_transactions')
    op.drop_table('auth0_states')
    # ### end Alembic commands ###
