"""Add image upload support: ta.image_upload_enabled + chat_message.image_data

Revision ID: bb7aae3428a8
Revises: 8345109cf060
Create Date: 2026-04-27 16:39:12.237753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7aae3428a8'
down_revision = '8345109cf060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('image_mime', sa.String(length=64), nullable=True))

    with op.batch_alter_table('teaching_assistants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_upload_enabled', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teaching_assistants', schema=None) as batch_op:
        batch_op.drop_column('image_upload_enabled')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_column('image_mime')
        batch_op.drop_column('image_data')

    # ### end Alembic commands ###
